01:41:49,530 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    success = bot.create_roa(args.prefix, args.asn, args.maxPrefixLength)
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 120, in create_roa
    self.browser.find_element(By.ID, 'crearROA').click()
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: Element <input id="crearROA" class="btn btn-primary" name="p::submit" type="submit"> is not clickable at point (815,588) because another element <iframe id="launcher"> obscures it

01:58:37,398 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 217, in <module>
    success = bot.create_roa(args.prefix, args.asn, args.maxPrefixLength)
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 123, in create_roa
    self.browser.find_element(By.ID, 'crearROA').click()
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: Element <input id="crearROA" class="btn btn-primary" name="p::submit" type="submit"> is not clickable at point (815,588) because another element <iframe id="launcher"> obscures it

17:10:55,652 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 222, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
14:49:42,686 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 222, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
15:30:43,993 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 222, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
17:08:52,977 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 222, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
12:36:17,74 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 222, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
16:24:58,935 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 222, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
14:39:17,129 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 222, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
17:11:19,458 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 222, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
14:16:58,382 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 222, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
16:01:04,155 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 222, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
15:22:24,118 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 222, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
14:06:36,10 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 222, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
16:09:58,201 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 222, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
16:32:23,604 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 222, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
13:36:15,795 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 222, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
13:22:11,16 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 222, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
16:38:32,913 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 222, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
14:18:23,171 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 222, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
14:27:50,398 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 222, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
13:12:25,694 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 222, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
14:01:35,449 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 222, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
13:08:46,278 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 222, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
17:07:12,642 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 222, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
15:35:50,72 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 222, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
12:27:02,280 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 222, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
16:40:36,377 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 222, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
02:38:52,194 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

17:31:27,539 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

07:30:27,698 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 55, in login
    display.start()
  File "/usr/lib/python3.9/site-packages/pyvirtualdisplay/display.py", line 72, in start
    self._obj.start()
  File "/usr/lib/python3.9/site-packages/pyvirtualdisplay/abstractdisplay.py", line 152, in start
    self._start1_has_displayfd()
  File "/usr/lib/python3.9/site-packages/pyvirtualdisplay/abstractdisplay.py", line 200, in _start1_has_displayfd
    self.display = int(self._wait_for_pipe_text(rfd))
  File "/usr/lib/python3.9/site-packages/pyvirtualdisplay/abstractdisplay.py", line 283, in _wait_for_pipe_text
    raise XStartError(
pyvirtualdisplay.abstractdisplay.XStartError: Xvfb program closed. command: ['Xvfb', '-br', '-nolisten', 'tcp', '-screen', '0', '2048x2048x24', '-displayfd', '6'] stderr: b'_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n'
07:30:27,763 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 55, in login
    display.start()
  File "/usr/lib/python3.9/site-packages/pyvirtualdisplay/display.py", line 72, in start
    self._obj.start()
  File "/usr/lib/python3.9/site-packages/pyvirtualdisplay/abstractdisplay.py", line 152, in start
    self._start1_has_displayfd()
  File "/usr/lib/python3.9/site-packages/pyvirtualdisplay/abstractdisplay.py", line 200, in _start1_has_displayfd
    self.display = int(self._wait_for_pipe_text(rfd))
  File "/usr/lib/python3.9/site-packages/pyvirtualdisplay/abstractdisplay.py", line 283, in _wait_for_pipe_text
    raise XStartError(
pyvirtualdisplay.abstractdisplay.XStartError: Xvfb program closed. command: ['Xvfb', '-br', '-nolisten', 'tcp', '-screen', '0', '2048x2048x24', '-displayfd', '6'] stderr: b'_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n'
07:30:27,763 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 55, in login
    display.start()
  File "/usr/lib/python3.9/site-packages/pyvirtualdisplay/display.py", line 72, in start
    self._obj.start()
  File "/usr/lib/python3.9/site-packages/pyvirtualdisplay/abstractdisplay.py", line 152, in start
    self._start1_has_displayfd()
  File "/usr/lib/python3.9/site-packages/pyvirtualdisplay/abstractdisplay.py", line 200, in _start1_has_displayfd
    self.display = int(self._wait_for_pipe_text(rfd))
  File "/usr/lib/python3.9/site-packages/pyvirtualdisplay/abstractdisplay.py", line 283, in _wait_for_pipe_text
    raise XStartError(
pyvirtualdisplay.abstractdisplay.XStartError: Xvfb program closed. command: ['Xvfb', '-br', '-nolisten', 'tcp', '-screen', '0', '2048x2048x24', '-displayfd', '6'] stderr: b'_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n'
07:30:27,768 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 55, in login
    display.start()
  File "/usr/lib/python3.9/site-packages/pyvirtualdisplay/display.py", line 72, in start
    self._obj.start()
  File "/usr/lib/python3.9/site-packages/pyvirtualdisplay/abstractdisplay.py", line 152, in start
    self._start1_has_displayfd()
  File "/usr/lib/python3.9/site-packages/pyvirtualdisplay/abstractdisplay.py", line 200, in _start1_has_displayfd
    self.display = int(self._wait_for_pipe_text(rfd))
  File "/usr/lib/python3.9/site-packages/pyvirtualdisplay/abstractdisplay.py", line 283, in _wait_for_pipe_text
    raise XStartError(
pyvirtualdisplay.abstractdisplay.XStartError: Xvfb program closed. command: ['Xvfb', '-br', '-nolisten', 'tcp', '-screen', '0', '2048x2048x24', '-displayfd', '6'] stderr: b'_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n'
07:30:27,768 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 55, in login
    display.start()
  File "/usr/lib/python3.9/site-packages/pyvirtualdisplay/display.py", line 72, in start
    self._obj.start()
  File "/usr/lib/python3.9/site-packages/pyvirtualdisplay/abstractdisplay.py", line 152, in start
    self._start1_has_displayfd()
  File "/usr/lib/python3.9/site-packages/pyvirtualdisplay/abstractdisplay.py", line 200, in _start1_has_displayfd
    self.display = int(self._wait_for_pipe_text(rfd))
  File "/usr/lib/python3.9/site-packages/pyvirtualdisplay/abstractdisplay.py", line 283, in _wait_for_pipe_text
    raise XStartError(
pyvirtualdisplay.abstractdisplay.XStartError: Xvfb program closed. command: ['Xvfb', '-br', '-nolisten', 'tcp', '-screen', '0', '2048x2048x24', '-displayfd', '6'] stderr: b'_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n'
2021-12-24 16:53:02,946 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2021-12-25 03:10:25,44 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2021-12-25 14:52:02,527 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2021-12-26 05:02:05,598 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2021-12-26 12:54:38,523 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2021-12-27 04:38:11,658 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2021-12-27 17:13:25,984 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2021-12-28 00:28:28,605 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2021-12-28 16:11:34,500 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2021-12-29 02:39:23,689 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2021-12-29 12:46:01,565 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2021-12-30 01:28:41,134 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2021-12-30 13:09:59,563 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2021-12-31 01:45:27,353 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2021-12-31 12:57:49,957 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-01-01 00:32:15,749 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-01-01 12:55:46,662 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-01-02 05:44:41,139 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-01-02 15:03:56,791 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-01-03 02:59:32,2 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-01-03 16:59:50,882 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-01-04 05:58:18,157 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-01-04 13:10:30,261 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-01-05 03:47:43,702 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-01-05 17:10:08,305 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-01-06 05:56:41,559 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-01-06 15:13:12,686 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-01-07 04:54:12,237 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-01-07 16:32:53,907 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-01-08 00:18:15,327 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-01-08 13:51:47,535 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-01-09 04:16:43,790 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-01-09 15:11:26,454 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-01-10 02:18:31,486 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-01-10 14:01:27,554 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-01-11 03:26:48,957 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-01-11 17:33:31,160 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-01-12 03:38:47,354 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-01-12 12:37:44,360 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-01-13 01:59:08,856 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-01-13 13:29:05,686 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-01-14 00:48:16,840 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-01-14 15:27:55,423 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-01-15 00:56:08,127 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-01-15 17:45:26,456 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-01-16 00:02:05,612 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-01-16 16:22:53,698 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-01-17 01:27:49,661 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-01-17 14:40:58,886 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-01-18 02:13:47,438 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-01-18 13:23:25,568 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-01-19 01:57:44,857 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-01-19 15:38:04,468 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-01-20 02:09:47,968 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 214, in <module>
    if bot.login():
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 71, in login
    WebDriverWait(self.browser, timeout=60).until(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-01-20 13:55:58,242 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 192, in <module>
    success = bot.delete_roa(args.prefix, args.asn)
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 112, in delete_roa
    assert rnode is not None
AssertionError
2022-01-21 05:47:45,907 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 190, in <module>
    success = bot.create_roa(args.prefix, args.asn, args.maxPrefixLength)
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 65, in create_roa
    assert rnode is not None
AssertionError
2022-01-21 14:44:21,605 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 192, in <module>
    success = bot.delete_roa(args.prefix, args.asn)
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 112, in delete_roa
    assert rnode is not None
AssertionError
2022-01-22 03:44:32,574 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 190, in <module>
    success = bot.create_roa(args.prefix, args.asn, args.maxPrefixLength)
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 65, in create_roa
    assert rnode is not None
AssertionError
2022-01-22 14:46:19,181 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 192, in <module>
    success = bot.delete_roa(args.prefix, args.asn)
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 112, in delete_roa
    assert rnode is not None
AssertionError
2022-01-23 02:43:27,425 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 190, in <module>
    success = bot.create_roa(args.prefix, args.asn, args.maxPrefixLength)
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 65, in create_roa
    assert rnode is not None
AssertionError
2022-01-23 16:32:31,265 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 192, in <module>
    success = bot.delete_roa(args.prefix, args.asn)
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 112, in delete_roa
    assert rnode is not None
AssertionError
2022-01-24 01:57:51,577 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 190, in <module>
    success = bot.create_roa(args.prefix, args.asn, args.maxPrefixLength)
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 65, in create_roa
    assert rnode is not None
AssertionError
2022-01-24 14:19:54,48 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 192, in <module>
    success = bot.delete_roa(args.prefix, args.asn)
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 112, in delete_roa
    assert rnode is not None
AssertionError
2022-01-25 02:35:08,524 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 190, in <module>
    success = bot.create_roa(args.prefix, args.asn, args.maxPrefixLength)
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 65, in create_roa
    assert rnode is not None
AssertionError
2022-01-25 15:15:55,318 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 192, in <module>
    success = bot.delete_roa(args.prefix, args.asn)
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 112, in delete_roa
    assert rnode is not None
AssertionError
2022-01-26 02:48:14,310 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 190, in <module>
    success = bot.create_roa(args.prefix, args.asn, args.maxPrefixLength)
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 65, in create_roa
    assert rnode is not None
AssertionError
2022-01-26 14:39:53,605 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 192, in <module>
    success = bot.delete_roa(args.prefix, args.asn)
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 112, in delete_roa
    assert rnode is not None
AssertionError
2022-01-27 05:24:11,63 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 190, in <module>
    success = bot.create_roa(args.prefix, args.asn, args.maxPrefixLength)
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 65, in create_roa
    assert rnode is not None
AssertionError
2022-01-27 12:48:19,17 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 192, in <module>
    success = bot.delete_roa(args.prefix, args.asn)
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 112, in delete_roa
    assert rnode is not None
AssertionError
2022-01-28 04:03:04,22 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 190, in <module>
    success = bot.create_roa(args.prefix, args.asn, args.maxPrefixLength)
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 65, in create_roa
    assert rnode is not None
AssertionError
2022-01-28 13:27:23,116 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 192, in <module>
    success = bot.delete_roa(args.prefix, args.asn)
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 112, in delete_roa
    assert rnode is not None
AssertionError
2022-01-29 04:33:17,27 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 190, in <module>
    success = bot.create_roa(args.prefix, args.asn, args.maxPrefixLength)
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 65, in create_roa
    assert rnode is not None
AssertionError
2022-01-29 13:54:56,294 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 192, in <module>
    success = bot.delete_roa(args.prefix, args.asn)
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 112, in delete_roa
    assert rnode is not None
AssertionError
2022-01-30 00:45:34,425 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 190, in <module>
    success = bot.create_roa(args.prefix, args.asn, args.maxPrefixLength)
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 65, in create_roa
    assert rnode is not None
AssertionError
2022-01-30 12:23:51,928 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 192, in <module>
    success = bot.delete_roa(args.prefix, args.asn)
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 112, in delete_roa
    assert rnode is not None
AssertionError
2022-01-31 01:22:16,977 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 190, in <module>
    success = bot.create_roa(args.prefix, args.asn, args.maxPrefixLength)
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 64, in create_roa
    rnode = self.rtree.search_best(prefix)
ValueError: Name or service not known
2022-01-31 01:56:51,285 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 190, in <module>
    success = bot.create_roa(args.prefix, args.asn, args.maxPrefixLength)
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 65, in create_roa
    assert rnode is not None
AssertionError
2022-04-08 05:21:50,274 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 185, in <module>
    bot = Bot(config_fname=args.config)
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 26, in __init__
    self.auth_url = config['auth_url']
KeyError: 'auth_url'
2022-04-08 05:22:30,154 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 185, in <module>
    bot = Bot(config_fname=args.config)
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 26, in __init__
    self.auth_url = config['auth_url']
KeyError: 'auth_url'
2022-07-11 02:13:31,674 root ERROR Error
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f893a579670>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='registro.api.lacnic.net', port=443): Max retries exceeded with url: /lacnic/2.0/rpki/roas (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f893a579670>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 190, in <module>
    success = bot.create_roa(args.prefix, args.asn, args.maxPrefixLength)
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 89, in create_roa
    api_resp = self.api.post(
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests_oauthlib/oauth2_session.py", line 515, in request
    return super(OAuth2Session, self).request(
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='registro.api.lacnic.net', port=443): Max retries exceeded with url: /lacnic/2.0/rpki/roas (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f893a579670>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2022-07-11 14:24:41,227 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-09-07 05:11:52,818 root ERROR Error
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7ff527571670>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='registro.api.lacnic.net', port=443): Max retries exceeded with url: /lacnic/2.0/rpki/roas (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff527571670>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 190, in <module>
    success = bot.create_roa(args.prefix, args.asn, args.maxPrefixLength)
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 89, in create_roa
    api_resp = self.api.post(
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests_oauthlib/oauth2_session.py", line 515, in request
    return super(OAuth2Session, self).request(
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='registro.api.lacnic.net', port=443): Max retries exceeded with url: /lacnic/2.0/rpki/roas (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff527571670>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2022-09-07 14:22:02,358 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-09-09 16:34:20,961 root ERROR Error
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fd6a15f3580>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='registro.api.lacnic.net', port=443): Max retries exceeded with url: /lacnic/2.0/rpki/roas?asn=3970 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd6a15f3580>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 192, in <module>
    success = bot.delete_roa(args.prefix, args.asn)
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 120, in delete_roa
    api_resp = self.api.get(
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests_oauthlib/oauth2_session.py", line 515, in request
    return super(OAuth2Session, self).request(
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='registro.api.lacnic.net', port=443): Max retries exceeded with url: /lacnic/2.0/rpki/roas?asn=3970 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd6a15f3580>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2022-11-02 13:23:28,693 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-02 15:01:30,786 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-03 14:23:58,962 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-03 15:11:49,725 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-04 13:49:50,887 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-04 14:00:40,265 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-05 12:48:09,366 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-05 14:40:26,606 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-06 12:24:37,704 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-06 17:30:19,284 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-07 14:19:34,75 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-07 17:18:35,694 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-08 14:28:27,594 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-08 17:28:53,802 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-09 15:38:27,589 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-09 16:22:51,481 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-10 15:06:01,626 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-10 16:35:15,227 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-11 12:38:10,913 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-11 15:32:53,185 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-12 12:20:39,463 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-12 16:06:14,905 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-13 15:13:44,59 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-13 15:22:12,832 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-14 12:48:43,40 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-14 15:24:46,774 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-15 12:42:56,286 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-15 15:20:50,821 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-16 13:25:52,613 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-16 15:58:23,641 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-17 13:07:06,592 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-17 16:11:13,148 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-18 14:09:15,796 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-18 14:19:37,796 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-19 14:44:22,179 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-19 16:49:08,901 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-20 12:18:17,608 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-20 13:46:08,103 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-21 13:44:37,496 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-21 17:15:35,373 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-22 13:24:35,626 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-22 16:06:50,237 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-23 14:29:55,354 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-23 17:03:24,377 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-24 14:56:49,908 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-24 15:45:48,238 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-25 12:39:18,638 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-25 16:38:41,413 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-26 13:54:32,966 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-26 14:13:00,177 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-27 12:47:14,634 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-27 13:36:28,280 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-28 13:50:14,162 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-28 15:01:19,727 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-29 14:21:32,164 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-29 14:48:09,882 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-30 15:40:21,9 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-11-30 17:04:33,904 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-12-01 14:51:43,889 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-12-01 16:21:14,371 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-12-02 13:00:00,880 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-12-02 16:10:46,971 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-12-03 14:44:50,796 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-12-03 15:46:44,650 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-12-04 17:28:24,500 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-12-04 17:49:05,11 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-12-05 13:41:37,483 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-12-05 15:35:45,898 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-12-06 13:19:04,543 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-12-06 16:12:19,399 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-12-07 12:32:33,158 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-12-07 15:09:19,427 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-12-08 12:29:19,818 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-12-08 15:39:41,407 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-12-09 14:13:53,761 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-12-09 16:39:00,560 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-12-10 15:09:22,989 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-12-10 16:08:43,824 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-12-11 12:23:29,585 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-12-11 14:21:58,772 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-12-12 13:26:04,93 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-12-12 17:45:14,535 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-12-13 12:49:16,184 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-12-13 15:24:26,416 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-12-14 14:46:17,224 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-12-14 17:59:47,319 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-12-15 12:26:25,263 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-12-15 12:58:24,273 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-12-16 14:40:18,616 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-12-16 15:29:19,315 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-12-17 12:53:25,516 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-12-17 16:20:21,29 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-12-18 13:09:58,221 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-12-18 13:51:11,989 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-12-19 14:14:30,993 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-12-19 16:21:55,479 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-12-20 17:08:57,279 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
2022-12-20 17:17:33,544 root ERROR Error
Traceback (most recent call last):
  File "/home/romain/Projects/perso/rov-timing-code/src/lacnic/bot.py", line 195, in <module>
    raise Exception(f'Failed to {args.action} ROA!')
Exception: Failed to delete ROA!
